version: '3.8'
services:
  t3-practice:
    container_name: t3-practice
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    env_file: .env
    ports:
      - '32880:8080' # NestJS
    command: sleep infinity
    depends_on:
        - t3-practice-db

  t3-practice-db:
    container_name: t3-practice-db
    image: mariadb:10.10.2-jammy
    restart: unless-stopped
    volumes:
      - t3-practice-db-volume:/var/lib/mariadb/
      - ../database/conf.d:/etc/mysql/conf.d
      - ../database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
      - '32890:3306'

volumes:
  t3-practice-db-volume:
    driver: local